	server_name: World Builder 2 Runtime
	server_bind_address: 127.0.0.1
	server_port: 43615
	ws_server_port: 43616
	client_version: 10048
	member_world: true
	based_map_data: 64
	want_myworld: false
	custom_landscape: false
	world_builder_mode: true
	world_builder_adaptive_mode: true
	layered_native_world_runtime_profile: adaptive-world-builder
	want_packet_register: false
